modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Full%20Brightness%20Toggle"
logoFile="icon.png"

[[mods]]
modId="fullbrightnesstoggle"
version="4.2"
displayName="Full Brightness Toggle"
displayURL="https://serilum.com/mod/full-brightness-toggle"
authors="Rick South"
description='''[Client] Press G to instantly toggle the brightness/gamma in-game to full.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., Nahuel Fernandez, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.fullbrightnesstoggle]]
    modId="collective"
    type="required"
    versionRange="[7.78,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fullbrightnesstoggle]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "fullbrightnesstoggle.mixins.json"